"""empty message

Revision ID: c58187c851fd
Revises: d4adcdb9ffb7
Create Date: 2021-06-25 17:30:14.821735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.elements import True_


# revision identifiers, used by Alembic.
revision = 'c58187c851fd'
down_revision = 'd4adcdb9ffb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
