"""empty message

Revision ID: 55528ba1cff8
Revises: 8972e94e8cd8
Create Date: 2021-06-28 22:03:50.924863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55528ba1cff8'
down_revision = '8972e94e8cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_list_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_list_id_fkey', 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###
